services:
  exporter:
    # reference the image tag you want to use
#    image: "ghcr.io/ejsuncy/ecowater_prometheus_exporter:0.1.0"
    # or build from the Dockerfile
    build: .
    ports:
      - "10003:10003"
    environment:
      ACCOUNT_USERNAME: "${ACCOUNT_USERNAME}"
      ACCOUNT_PASSWORD: "${ACCOUNT_PASSWORD}"
      TZ: "America/Denver"
    volumes:
      - ./volumes:/etc/exporter
